var quotes = [
    '"Be the change that you wish to see in the world." - Mahatma Gandhi',
    '"You\'ve gotta dance like there\'s nobody watching, Love like you\'ll never be hurt, Sing like there\'s nobody listening, And live like it\'s heaven on earth." - William W. Purkey',
    '"Imperfection is beauty, madness is genius and it\'s better to be absolutely ridiculous than absolutely boring." - Marilyn Monroe, Marilyn',
    '"Do not go where the path may lead, go instead where there is no path and leave a trail." - Ralph Waldo Emerson',
    '"None but ourselves can free our minds." - Bob Marley',
    '"A ship is safe in harbor, but that\'s not what ships are for." - William G.T. Shedd',
    '"It\'s not the load that breaks you down, it\'s the way you carry it." - Lou Holtz',
    '"Hold fast to dreams, For if dreams die Life is a broken-winged bird, That cannot fly." - Langston Hughes',
    '"It\'s so hard to forget pain, but it\'s even harder to remember sweetness. We have no scar to show for happiness. We learn so little from peace." - Chuck Palahniuk',
    '"Count your age by friends, not years. Count your life by smiles, not tears." - John Lennon',
    '"The supreme art of war is to subdue the enemy without fighting." - Sun Tzu',
    '"Know thy self, know thy enemy. A thousand battles, a thousand victories." Sun Tzu',
    '"Regard your soldiers as your children, and they will follow you into the deepest valleys; look on them as your own beloved sons, and they will stand by you even unto death." - Sun Tzu',
    '"Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent\'s fate." - Sun Tzu',
    '"Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win." - Sun Tzu',
    '"If you are far from the enemy, make him believe you are near." - Sun Tzu',
    '"A people without the knowledge of their past history, origin and culture is like a tree without roots." - Marcus Garvey',
    '"I like the dreams of the future better than the history of the past." - Thomas Jefferson',
    '"Our greatest glory is not in never falling, but in rising every time we fall." - Confucius',
    '"I believe that imagination is stronger than knowledge. That myth is more potent than history. That dreams are more powerful than facts. That hope always triumphs over experience. That laughter is the only cure for grief. And I believe that love is stronger than death." - Robert Fulghum',
    '"Those who do not remember the past are condemned to repeat it." - George Santayana',
    '"Letting go means to come to the realization that some people are a part of your history, but not a part of your destiny." - Steve Maraboli',
    '"If you don\'t know history, then you don\'t know anything. You are a leaf that doesn\'t know it is part of a tree." - Michael Crichton',
    '"I can only note that the past is beautiful because one never realises an emotion at the time. It expands later, and thus we don\'t have complete emotions about the present, only about the past." - Virginia Woolf',
    '"Remember, remember always, that all of us, and you and I especially, are descended from immigrants and revolutionists." - Franklin D. Roosevelt',
    '"History is a set of lies agreed upon." - Napoléon Bonaparte',
    '"The soul becomes dyed with the colour of its thoughts." - Marcus Aurelius, Meditations',
    '"Your worst enemy could be your best friend, and your best friend your worst enemy." - Bob Marley',
    '"Don\'t worry about a thing, every little thing is gonna be alright." - Bob Marley',
    '"Conquer the devils with a little thing called love!" - Bob Marley',
    '"When you smoke the herb, it reveals you to yourself." - Bob Marley',
    '"Don\'t gain the world and lose your soul, wisdom is better than silver or gold..." - Bob Marley',
    '"Every man gotta right to decide his own destiny" - Bob Marley',
    '"The whole secret of existence is to have no fear. Never fear what will become of you, depend on no one. Only the moment you reject all help you are freed." - Buddha',
    '"You yourself, as much as anybody in the entire universe, deserve your love and affection." - Buddha',
    '"Peace comes from within. Do not seek it without." - Buddha',
    '"Neither fire nor wind, birth  nor death can erase our good deeds." - Buddha',
    '"Be vigilant; guard your mind against negative thoughts." - Buddha',
    '"A good friend who points out mistakes and imperfections and rebukes evil is to be respected as if he reveals a secret of hidden treasure." - Buddha',
    '"All that we are is the result of what we have thought. The mind is everything. What we think we become." - Buddha',
    '"It is wrong to think that misfortunes come from the east or the west; they originate within one\'s mind. Therefore, it is foolish to gaurd against misfortunes from the external world and leave the inner mind uncontrolled." - Buddha',
    '"Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared." - Buddha',
    '"Those who really seek the path of Enlightenment dictate terms to their mind. Then they proceed with strong determination." - Buddha ',
    '"It is better to conquer yourself than to win a thousand battles. Then the victory is yours. It cannot be taken from you, not by angels or by demons, heaven or hell." - Budda',
    '"As the Fletcher whittles and makes straight his arrows, so the master directs his straying thoughts." - Buddha',
    '"There is nothing more dreadful than the habit of doubt. Doubt separates people. It is a poison that disintegrates friendships and breaks up pleasant relations. It is a thorn that irritates and hurts; it is a sword that kills." - Buddha',
    '"A wise man, recognizing that the world is but an illusion, does not act as if it is real, so he escapes the suffering." - Buddha',
    '"To keep the body in good health is a duty...otherwise we shall not be able to keep our mind strong and clear." - Buddha',
    '"Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment." - Buddha',
    '"Let yourself be open and life will be easier. A spoon of salt in a glass of water makes the water undrinkable. A spoon of salt in a lake is almost unnoticed." - Buddha',
    '"The secret of health for both mind and body is not to mourn for the past, worry about the future, or anticipate troubles, but to live in the present moment wisely and earnestly." - Buddha'
];

function newQuote() {
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
